support webrtc trickle
libp2p/js-libp2p-webrtc-star pull request #282
Opened 2020-12-04 09:32 UTC by lovemyliwu

2020-12-07 13:19 UTC, vasco-santos commented
@lovemyliwu can you add some tests for this support?

2020-12-08 02:00 UTC, lovemyliwu commented
Sure, already start the process, I'll mention you after done

2020-12-08 08:33 UTC, lovemyliwu commented
@vasco-santos please review

2020-12-08 11:36 UTC, vasco-santos requested changes
Thanks for this PR! Left some feedback

2020-12-08 11:36 UTC, vasco-santos commented on src/listener.js
> +        listener.__pendingIntents.get(offer.intentId).push(offer)
Will it be possible for this get to be undefined?

2020-12-08 11:36 UTC, vasco-santos commented on src/listener.js
> +        listener.__spChannels.get(offer.intentId).signal(offer.signal)
Can we do a get before the if clause, and use that constant in the if instead of `has` + `get` operations?

2020-12-08 11:36 UTC, vasco-santos commented on src/listener.js
>        channel.once('connect', async () => {
We should probably do cleaning here? Otherwise `__spChannels` and `__pendingIntents` will grow forever causing memory issues in the long run

2020-12-09 02:08 UTC, lovemyliwu commented on src/listener.js
>        channel.once('connect', async () => {
No, the ice candidate may received after connect event.

We can do cleaning in the `channel.once(close)` event handler.

2020-12-09 02:35 UTC, lovemyliwu commented on src/listener.js
>        channel.once('connect', async () => {
the best point is `untrackConn`

2020-12-09 02:43 UTC, lovemyliwu commented
@vasco-santos please review

2020-12-09 10:15 UTC, vasco-santos commented on src/listener.js
>        channel.once('connect', async () => {
yes, `untrackConn` seems the best place! 👍🏼

2020-12-09 10:21 UTC, vasco-santos approved these changes
LGTM!
Thanks for adding this @lovemyliwu

2020-12-09 10:21 UTC, merged